version: '3.8'

services:
  ws-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    restart: unless-stopped
    networks:
      - wivroosearch-network
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}

networks:
  wivroosearch-network:
    driver: bridge